config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks

  # # As a user, I can list tasks
  # get '/tasks', to: 'tasks#index'

  # # As a user, I can add a new task (show form)
  # get '/tasks/new', to: 'tasks#new', as: :new_task

  # # As a user, I can view the details of a task
  # get '/tasks/:id', to: 'tasks#show', as: :task

  # # As a user, I can add a new task (submit form)
  # post '/tasks', to: 'tasks#create'

  # # As a user, I can edit a task (see the form)
  # get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  # # As a user, I can edit a task (submit the form)
  # patch '/tasks/:id', to: 'tasks#update'

  # # As a user, I can remove a task
  # delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :read_id, only: [:show, :edit, :update, :destroy]

  # As a user, I can list tasks
  def index
    @tasks = Task.all
  end

  # As a user, I can view the details of a task
  def show
    # @task = Task.find(params[:id])
  end

  # As a user, I can add a new task (show form)
  def new
    @task = Task.new
  end

  # As a user, I can add a new task (submit form)
  def create
    @task = Task.create(task_params)
    # after i create the instance i redirect to its show page
    redirect_to task_path(@task.id)
  end

  # As a user, I can edit a task (see the form)
  def edit
    # @task = Task.find(params[:id])
  end

  # As a user, I can edit a task (submit the form)
  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task.id)
  end

  # As a user, I can remove a task
  def destroy
    # @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  # strong params
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def read_id
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
  <%= form_for task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'i.e. Buy groceries' %>

    <%= f.label :details %>
    <%= f.text_field :details, placeholder: 'i.e. Need bread!' %>

    <%# show the completed checkbox only when you edit a task %>
    <% if params[:action] == 'edit' %>
      <%= f.label :completed %>
      <%= f.check_box  :completed %>
      <% task.completed = true %>
    <% end %>


    <%= f.submit %>
  <% end %>

app/views/tasks/edit.html.erb
<div class="container">

  <h1>Edit a task</h1>

  <%= render "form", task: @task %>

  <%= link_to('Back to list', tasks_path) %>

</div>

app/views/tasks/index.html.erb
<div class="container">

  <h1>My tasks</h1>

  <ul class="list-nodots">
    <% @tasks.each do |task| %>
      <li><%= task.completed ? "[X]" : "[ ]" %>  <%= link_to(task.title, task_path(task.id)) %> <%= link_to("🗑︎", task_path(task.id), method: :delete, data: {confirm: "Are you sure you want to delete that?"} ) %></li>
    <% end %>
  </ul>

  <%= link_to("+ Add a new task", new_task_path) %>

</div>

app/views/tasks/new.html.erb
<div class="container">

  <h1>Add a new task</h1>

  <%= render "form", task: @task %>

  <%= link_to('Back to list', tasks_path) %>

</div>

app/views/tasks/show.html.erb
<div class="container">

  <h1><%= @task.title %></h1>

  <%= link_to("Edit this task", edit_task_path(@task.id))  %>

  <p><%= @task.details %></p>
  <p>This task is <%= @task.completed ? 'completed' : 'not completed yet' %>.</p>

  <%= link_to("Back to list", tasks_path)  %>

</div>